### PR TITLE
Fex fixes

### PR DESCRIPTION
**Pull request by apritzel**
The sunxi-tools "make check" target fetches the FEX files from this sunxi-boards repository, and fails on compiling some of them. To me those look more like bugs in the FEX files rather than fexc compiler issues, so try to fix those issues here.

### CODE REVIEW

**Comment by apritzel** [comment]
@libv @Icenowy Can you have a look at those fixes please? I couldn't care less about FEX, but sunxi-tools pulls in this repo for testing purposes, so I'd like to have this fixed, to avoid carrying patches there.

**Review by Icenowy — COMMENTED** [review]
This semicolon is from Allwinner BSP, and at least the FEX parser in their BSP can handle it.

Should we get able to handle it too?

**Comment by apritzel** [comment]
> This semicolon is from Allwinner BSP, and at least the FEX parser in their BSP can handle it.

Ah, thanks, that was one of my questions!

> Should we get able to handle it too?

Yes, I think so. I guess we can try to treat the semicolon as "rest of the line is comment" then, I will have a look what that would take.

**Comment by apritzel** [comment]
@Icenowy so it's a bit nasty. First the parser is somewhat ... interestingly written, it would really benefit from some rewrite, possibly by first tokenizing the input, the processing it. But as this is about FEX, I can't be asked ...
Just terminating a line at a semicolon is not easily possible, as it could appear in a string, I guess, and with the current code that's tricky to handle. So I was just trimming it off after the call to rtrim(), which means it just handles this special case when a line ends in a semicolon. So that works nicely, but reveals a bigger issue: Now the de-compilation of course misses the semicolon, so the diff between that and the original source doesn't come back clean, making the test fail.
So, either:
1) we remove the semicolons as an extra patch after extracting sunxi-boards.zip, just for the sake of "make check", but add the capability of dealing with a trailing semicolon to the parser anyway, or
2)  we add the capability of dealing with a trailing semicolon not only to script_fex.c, but also to unify_fex.c, so that the semicolon is trimmed from the pre-processed input, to make the "diff" match
3) some other hack

**Comment by apritzel** [comment]
I decided to fix up both script_fex.c and unify_fex.c in sunxi-tools, to explicitly deal with a trailing semicolon. Not super elegant, but allows those .fex files here to stay close to the originals.
So this updated PR removes the one patch that cut off the trailing semicolon from the .fex files.

**Pull request merged**
