### PR TITLE
add mixtile-loftq configs

### PR DESCRIPTION
**Pull request by pengphei**
The Mixtile LOFT-Q is A31 (sun6i) based prototyping board with 2G of RAM, 8G emmc, HDMI output, toslink speaker, microphone input, Ethernet and Wifi & BT, SD plug and SATA storage, 4xUSB host, and zigbee supporting with NXP JN5168.

### CODE REVIEW

**Comment by libv** [comment]
Repo vanished, device page is a mess. Yet another $hitpi that died as quickly as it came into existence.

**Comment by libv** [comment]
My bad, this apparently does not need a repo, and i can pull directly from the main repo pull requests. Fetched, renamed, chown, pushed. The device page is still an appalling mess.

**Comment by pengphei** [comment]
@libv this board is deprecated, you can ignore this device anyway.

**Comment by libv** [comment]
It was shipped, amazon claims to still have it, users have it, information should be thrown away.

**Comment by pengphei** [comment]
@libv , regards for you reminding, I will try claiming the information from the vendor. ;)

**Pull request closed without merging**
